Online Course/OnlineCourse/OnlineCourse/urls.py

from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('courses.urls')),
]

Online Course/OnlineCourse/courses/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from courses.views import home,coursePage,SignupView,LoginView,signout,checkout

from OnlineCourse.settings import MEDIA_URL, MEDIA_ROOT
urlpatterns = [


    # path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('logout',signout,name='logout'),

    path('signup',SignupView.as_view(),name='signup'),
    path('login',LoginView.as_view(),name='login'),
    path('course/<str:slug>',coursePage,name='coursePage'),
    path('check-out/<str:slug>',checkout,name='checkout'),



    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

Online Course/OnlineCourse/courses/models.py
from django.db import models

# Create your models here.

Online Course/OnlineCourse/courses/models/course.py
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=50,null=False)
    slug = models.CharField(max_length=50,null=False,unique=True)
    description = models.CharField(max_length=200,null=True)
    price = models.IntegerField(null=False)
    discount = models.IntegerField(null=False,default=0)
    active = models.BooleanField(default=False)
    thumbnail= models.ImageField(upload_to='files/thumbnail')
    date = models.DateTimeField(auto_now_add=True)
    resource = models.FileField(upload_to='files/resource')
    length = models.IntegerField(null=False)

    def __str__(self):
        return self.name
    



class CourseProperty(models.Model):
    description = models.CharField(max_length=20,null=False)
    course = models.ForeignKey(Course,null=False,on_delete=models.CASCADE)
    class Meta:
        abstract= True


class Tag(CourseProperty):
    pass
    

class Prerequisite(CourseProperty):
    pass
    
class Learning(CourseProperty):
    pass
    

Online Course/OnlineCourse/courses/models/payment.py
from django.db import models
from courses.models import Course,UserCourse
from django.contrib.auth.models import User

class Payment(models.Model):
    order_id = models.CharField(max_length=50,null=False)
    payment_id = models.CharField(max_length=50)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)

    user_course = models.ForeignKey(UserCourse,null=True,blank=True,on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)




    

Online Course/OnlineCourse/courses/models/user_course.py
from django.db import models
from courses.models import Course
from django.contrib.auth.models import User

class UserCourse(models.Model):
    user = models.ForeignKey(User,null=False,on_delete=models.CASCADE)
    course = models.ForeignKey(Course,null=False,on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.user.username} - {self.course.name}'

Online Course/OnlineCourse/courses/models/video.py
from django.db import models
from courses.models import Course
class Video(models.Model):
    title = models.CharField(max_length=100,null=False)
    course = models.ForeignKey(Course,null=False,on_delete=models.CASCADE)
    serial_number = models.IntegerField(null=False)
    video_id = models.CharField(max_length=20,null=False)
    is_preview = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    

    

Online Course/OnlineCourse/courses/forms/login_form.py
from django.contrib.auth.forms import AuthenticationForm
from django.forms import ValidationError
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import authenticate,login


class LoginForm(AuthenticationForm):
    username = forms.EmailField(max_length=25,required=True,label='Email')

    def clean(self):
        email = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = None
        try:
            user = User.objects.get(email=email)
            result = authenticate(username = user.username, password = password)

            if (result is not None):
                login(self.request,result)
                return result
            else:
                raise ValidationError("Email or password invalid")
        except:
            raise ValidationError("Email or Password invalid")

    
    

Online Course/OnlineCourse/courses/forms/registration_forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ValidationError
from django.contrib.auth.models import User
from django import forms
class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=20,required=True)
    last_name = forms.CharField(max_length=20,required=True)
    email = forms.EmailField(max_length=50,required=True)

    class Meta:
        model = User
        fields = ["first_name","last_name",'username',"email","password1","password2"]

    def clean_email(self):
        email1 = self.cleaned_data['email']
        user = None
        try:
            user = User.objects.get(email = email1)
        except:
            return email1
        if(user is not None):
            raise ValidationError('User already exists')

Online Course/OnlineCourse/courses/views/checkout.py
from django.shortcuts import render,redirect
from time import time
from courses.models import Course,Video,Payment
from OnlineCourse.settings import *
from django.shortcuts import HttpResponse
import razorpay
client = razorpay.Client(auth=(KEY_ID, KEY_SECRET))


def checkout(request,slug):
    course = Course.objects.get(slug = slug)
    user = None
    if(request.user.is_authenticated is False):
        return redirect("login")
    user = request.user
    action = request.GET.get('action')
    order = None
    payment = None
    if action == 'create_payment':
        amount = int((course.price - (course.price * course.discount * 0.01))*100)
        currency = "INR"
        notes = {
            "email":user.email,
            "name":f'{user.first_name}{user.last_name}',}
        reciept = f"codewithkrishna-{int(time())}"
        order = client.order.create({"notes" : notes,"amount" : amount,"currency" : currency})

        payment = Payment()
        payment.user = user
        payment.course = course
        payment.order_id = order.get('id')
        payment.save()



        
        

        
    context = {
        'course':course,
        'order':order,
        "payment":payment

    }
    return render(request,'courses/check_out.html',context)

Online Course/OnlineCourse/courses/views/courses.py
from django.shortcuts import render,redirect

from courses.models import Course,Video

from django.shortcuts import HttpResponse


def coursePage(request,slug):
    print(request.user)
    course = Course.objects.get(slug = slug)
    serial_number = request.GET.get('lecture')
    print(serial_number)
    if serial_number is None:
        serial_number = 1
    video = Video.objects.get(serial_number = serial_number, course  = course)
    if(request.user.is_authenticated is False and video.is_preview is False):
        return redirect("login")
    context = {
        'course':course,
        'video': video,

    }
    return render(request,'courses/course_page.html',context)

Online Course/OnlineCourse/courses/views/homepage.py
from django.shortcuts import render

from courses.models import Course

from django.shortcuts import HttpResponse


def home(request):
    courses = Course.objects.all()
    print(courses)
    context = {'course':courses}
    return render(request,'courses/home.html',context )

Online Course/OnlineCourse/courses/templates/courses/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"/>

      <link rel="stylesheet" href="{% static 'courses/css/common.css' %}">


    <title>{% block title %} {% endblock title %}</title>
    {% block css %}
    
    {% endblock css %}
  </head>
  <body>
    <div>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/"
                >Home <span class="sr-only">(current)</span></a
              >
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
               <li class="nav-item">
              <a class="nav-link" href="/logout">Logout</a>

            


             {% else %} 
                   <li class="nav-item">
              <a class="nav-link" href="/login">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/signup">Signup</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>

    {% block content %} {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>

    {% block js %}{% endblock js %}
  </body>
</html>

Online Course/OnlineCourse/courses/templates/courses/check_out.html
{% extends 'courses/base.html' %}
{% load courses_custom_tags %}

{% block title %}Login{% endblock title %}
{% block content %}

<div class="container">

<br>

{% if order is not None %}
<h1>{{order}}</h1>
<br> <br> <br>
<h1>{{payment}}</h1>

{% endif %}


<br>
<div class='row '>
    <div class="col ml-auto">
  <div class="card mx-auto" style="width: 18rem;">
  <img src="{{course.thumbnail.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{course.name}}</h5>
    <p class="card-text">
      <span class='price'>
        Save : {{course.discount}} % 
        <br>
      <del>₹{{course.price}}</del> &nbsp;
      <span> ₹{% call_sellprice course.price course.discount %}</span>
      </span> 
    </p>
  </div>

  


</div>
</div>
<div class="col ">
    <div>
        <p style="font-size:35px;text-align:center">{{course.name}}</p>
        <hr>
        <p style="font-size:35px;text-align:center">Payable Amount : <b><span> ₹{% call_sellprice course.price course.discount %}</span></b> </p>
        <a class="btn btn-light border" href="?action=create_payment">Continue to Payment</a>

    </div>
</div>
</div>
</div>

{% endblock content %}


Online Course/OnlineCourse/courses/templates/courses/course_page.html
{% extends 'courses/base.html' %} 
{% load static %}
{% load courses_custom_tags %}

{% block title %}
Courses
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'courses/css/scrollBar.css' %}">

{% endblock css %}

{% block js %}

<script src="{% static 'courses/js/course_page.js' %}"></script>

{% endblock js %}
{% block content %}

<div class="container-float">
            {{video.video_id}}

  <div hidden>
    <p class="display-">Course Page : {{course.name}}</p>
    <p class="display-">Course Page : {{course.price}}</p>
    <p class="display-">Course Page : {{course.discount}}</p>
    <p class="display-">Course Page : {{course.description}}</p>
    <p class="display-">Course Page : {{course.thumbnail}}</p>
    <p class="display-">Course Page : {{course.video_set.all}}</p>
    <p class="display-">Course Page : {{course.tag_set.all}}</p>
    <p class="display-">Course Page : {{course.prerequisite_set.all}}</p>
    <p class="display-">Course Page : {{course.learning_set.all}}</p>
  </div>
  <div>
   <div class = "card p-3">
     <div class="row">
      <div class="col">
        <div class="mx-auto">

          <iframe id = "player" class='mx-auto'
            width="100%"
            height="315"
            src="https://www.youtube.com/embed/{{video.video_id}}"
            title="YouTube video player"
            frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowfullscreen autoplay = 'on'
          ></iframe>
        </div>
      </div>
      <div class="col-3">
        <ul id='video_list' class="list-group overflow-y-scroll">
          {% for video in course.video_set.all %}

          <li class="list-group-item"><a href="?lecture={{video.serial_number}}">{{video}}</a></li>

          {% endfor %}
        </ul>
      </div>
    </div>
   </div>

    <div class="mt-3">
      <div class="card" >
        <div class="card-body">
          <h5 class="card-title">{{course.name}}</h5>
          <p class="card-text">{{course.description}}</p>
        </div>
      </div>
    </div>
    <div class="mt-3">
      <div class="card" >
        <div class="card-body">
          <h5 class="card-title">Prerequisite : </h5>
          <p class="card-text">
            <ol>
                {% for pre in course.prerequisite_set.all %}

          <li >{{pre.description}}</li>

          {% endfor %}
            </ol>
        </p>
        </div>
      </div>
    </div>
     <div class="mt-3">
      <div class="card" >
        <div class="card-body">
          <h5 class="card-title">What you will learn :</h5>
          <p class="card-text">
            <ol>
                {% for pre in course.learning_set.all %}

          <li >{{pre.description}}</li>

          {% endfor %}
            </ol>
        </p>
        </div>
      </div>
    </div>
    <br> 
    <br>
    <br>
  </div>
</div>
</div>



  {% endblock content %}

  


Online Course/OnlineCourse/courses/templates/courses/home.html

{% extends 'courses/base.html' %}
{% load courses_custom_tags %}

{% block content %}


<style>
  .price{
    font-size : 20px;
  }
</style>

<div class="container-fluid">
  <br>

<div class="row">
{% for x in course %}


<div class="col mx-auto">
  <div class="card mx-auto" style="width: 18rem;">
  <img src="{{x.thumbnail.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{x.name}}</h5>
    <p class="card-text">
      <span class='price'>
        Save : {{x.discount}} % 
        <br>
      <del>₹{{x.price}}</del> &nbsp;
      <span> ₹{% call_sellprice x.price x.discount %}</span>
      </span> 
    </p>
  </div>

  <div class="card-footer p-0">

    <div class="row no-gutters">

      <div class='col border'>
      <a href="/check-out/{{x.slug}}" class="btn btn-light btn-block">Enroll Now</a>

      </div>

      <div class="col border">
      <a href="/course/{{x.slug}}" class="btn btn-light btn-block">Show More</a>

      </div>


    </div>
  </div>


</div>
</div>


{% endfor %}


</div>

</div>

{% endblock content %}

Online Course/OnlineCourse/courses/templates/courses/login.html
{% extends 'courses/base.html' %}
{% load courses_custom_tags %}
{% block title %}Login{% endblock title %}
{% block content %}

<div class="container">

<div class="display-1">Login Page</div>

<hr>
<div>
    <form action="/login" method='POST'>
        {% csrf_token %}
        {{form.as_p}}

        <input type="submit" value="Login">

    </form>
</div>
</div>

{% endblock content %}


Online Course/OnlineCourse/courses/templates/courses/signup.html
{% extends 'courses/base.html' %}
{% load courses_custom_tags %}
{% block title %}Signup{% endblock title %}
{% block content %}

<div class="container">

<div class="display-1">Signup Page</div>

<div>
    <form action="/signup" method='POST'>
        {% csrf_token %}
    {{form.as_ul}}
<input type="submit" value="Register">
    </form>
</div>
</div>

{% endblock content %}
